apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: {{ azure.tenant }}
  accessPolicy:
    inbound:
      rules:
      {{#each azureAccessInbound}}
          - application: {{this.application}}
            namespace: {{this.namespace}}
            cluster: {{this.cluster}}
      {{/each}}
    outbound:
      external:
        - host: {{ azure.familiebasak_url }}
        - host: {{ azure.familieefsak_url }}
        - host: {{ azure.bidraggcpproxy_url }}
        - host: {{ azure.bidragperson_url }}
        - host: {{ azure.familiekssak_url }}
        - host: {{ azure.inntektskomponenten_base_url }}
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi
    replicas:
      cpuThresholdPercentage: 80
      max: 4
      min: {{ spec.replicas.min }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: FAMILIEBASAK_URL
      value: https://{{ azure.familiebasak_url }}
    - name: FAMILIEBASAK_SCOPE
      value: {{ azure.familiebasak_scope }}
    - name: FAMILIEEFSAK_URL
      value: https://{{ azure.familieefsak_url }}
    - name: FAMILIEEFSAK_SCOPE
      value: {{ azure.familieefsak_scope }}
    - name: BIDRAGGCPPROXY_URL
      value: https://{{ azure.bidraggcpproxy_url }}
    - name: BIDRAGGCPPROXY_SCOPE
      value: {{ azure.bidraggcpproxy_scope }}
    - name: INNTEKTSKOMPONENTEN_URL
      value: https://{{ azure.inntektskomponenten_url }}
    - name: INNTEKTSKOMPONENTEN_SCOPE
      value: {{ azure.inntektskomponenten_scope }}
    - name: BIDRAGPERSON_URL
      value: https://{{ azure.bidragperson_url }}
    - name: BIDRAGPERSON_SCOPE
      value: {{ azure.bidragperson_scope }}
    - name: FAMILIEKSSAK_URL
      value: https://{{ azure.familiekssak_url }}
    - name: FAMILIEKSSAK_SCOPE
      value: {{ azure.familiekssak_scope }}
  gcp:
    sqlInstances:
      - name: {{ dbname }}
        type: POSTGRES_14
        databases:
          - name: {{ dbname }}
            envVarPrefix: DB
        tier: {{ spec.gcp.sqlInstances.tier }}
