name: bidrag-grunnlag
ingresses:
  - https://bidrag-grunnlag.intern.nav.no
azure:
  tenant: nav.no
  familiebasak_url: familie-ba-sak.intern.nav.no
  familiebasak_scope: prod-gcp.teamfamilie.familie-ba-sak
  familieefsak_url: familie-ef-sak.intern.nav.no
  familieefsak_scope: prod-gcp.teamfamilie.familie-ef-sak
  bidraggcpproxy_url: bidrag-gcp-proxy.prod-fss-pub.nais.io
  bidraggcpproxy_scope: prod-fss.bidrag.bidrag-gcp-proxy
  inntektskomponenten_base_url: team-inntekt-proxy.prod-fss-pub.nais.io
  inntektskomponenten_url: team-inntekt-proxy.prod-fss-pub.nais.io/proxy/inntektskomponenten
  inntektskomponenten_scope: prod-fss.team-inntekt.inntektskomponenten
  bidragperson_scope: prod-fss.bidrag.bidrag-person
  bidragperson_url: bidrag-person.prod-fss-pub.nais.io
  bidragperson_app: bidrag-person
  bidragperson_cluster: prod-fss
  familiekssak_scope: prod-gcp.teamfamilie.familie-ks-sak
  familiekssak_url: familie-ks-sak.intern.nav.no
  familiekssak_app: familie-ks-sak
dbname: bidrag-grunnlag-prod
azureAccessInbound:
  - application: bidrag-gcp-proxy
    namespace: bidrag
    cluster: prod-fss
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
spec:
  replicas:
    min: 2
  gcp:
    sqlInstances:
      tier: db-custom-1-3840